server.port=8080

# Datenbank
spring.datasource.url=jdbc:postgresql://db:5432/app
spring.datasource.username=app
spring.datasource.password=Sommer2023!

# Betrieb
management.endpoints.web.exposure.include=*
server.error.include-stacktrace=always
logging.level.org.springframework.jdbc=DEBUG
